---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev
    AllowedValues:
      - dev
      - prod
#  HostingStackName:
#    Type: String
#    Description: Stack name of the hosting stack
  CertificateArn:
    Type: String
    Description: ARN of ACM certificate to use for SSL
    Default: arn:aws:acm:us-east-1:427927161742:certificate/66066e1d-6aac-49f4-8b52-bd699547b8d6
Mappings:
  DNSSubdomainMap:
    prod:
      root: cf-test.cdn.byu.edu.
      alias: cf-test.cdn.byu.edu
    dev:
      root: dev.cdn.byu.edu.
      alias: dev.cdn.byu.edu
  BucketNames:
    prod:
      content: cdn.byu.edu
Resources:
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        Aliases:
         - !FindInMap [ DNSSubdomainMap, !Ref Environment, alias ]
        Enabled: 'true'
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: 'true'
            Headers: [Origin]
          TargetOriginId: only-origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        Origins:
        - Id: only-origin
          DomainName:
            Fn::Sub:
              - "${Bucket}.s3.amazonaws.com"
              - { Bucket: !FindInMap [BucketNames, !Ref Environment, content] }
          S3OriginConfig:
            OriginAccessIdentity: ''
  WebsiteDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !FindInMap [ DNSSubdomainMap, !Ref Environment, root ]
      Comment: DNS for CDN
      RecordSets:
        - Name: !FindInMap [ DNSSubdomainMap, !Ref Environment, root ]
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [WebsiteCDN, DomainName]
        - Name: !FindInMap [ DNSSubdomainMap, !Ref Environment, root ]
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt WebsiteCDN.DomainName

