# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: CDN Webhooks
  description: Hookman
  version: "1.0.0"
# the domain of the service
host: hooks.cdn.byu.edu
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /github:
    post:
      summary: Github web hook receiver
      operationId: githubHook
      responses:
        201:
          description: Okay
      x-amazon-apigateway-integration: 
#        credentials: ${stageVariables.GithubCallerRoleArn}
        responses: 
          default: 
            statusCode: "201"
        requestTemplates: 
          application/json: >
            {
              "source": "github",
              "callerIp": "$context.identity.sourceIp",
              "eventType": "$input.params('X-GitHub-Event')",
              "eventId": "$input.params('X-GitHub-Delivery')",
              "eventBody": $input.json('$')
            }
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:427927161742:function:${stageVariables.GithubLambdaName}/invocations
        httpMethod: POST
        type: aws
