---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev
    AllowedValues:
      - dev
      - prod
Mappings:
  Bucket:
    prod:
      name: cdn.byu.edu
    dev:
      name: byu-web-community-cdn-dev
  DNSSubdomainMap:
    prod:
      root: cdn.byu.edu.
      alias: cdn.byu.edu
    dev:
      root: dev.cdn.byu.edu.
      alias: dev.cdn.byu.edu
Resources:
  WebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./webhook-swagger.yml
      StageName: Prod
      Variables:
        GithubLambdaName: !Ref GithubHookFunction
    DependsOn: [GithubHookFunction]

  GithubHookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../
      Handler: lambda/github-hook.handler
      Runtime: nodejs4.3
      Timeout: 60
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref WebhookApi
            Path: /github
            Method: POST

Outputs:
#  TriggersApi:
#    Description: ARN of the API Endpoint
#    Value: !Ref WebhookApi
  GithubHookFunction:
    Description: Github hook function
    Value: !GetAtt GithubHookFunction.Arn
