version: 0.1

phases:
  pre_build:
    commands:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - yarn install
  # Insert stuff to set up the CDN
  build:
    commands:
      - node index.js

  post_build:
    commands:
      - echo "============ Syncing to ${DESTINATION_S3_BUCKET} ============"
      - aws s3 sync --delete .tmp/s3-staging/ s3://${DESTINATION_S3_BUCKET}/ --acl public-read

artifacts:
  files:
    - '**/*'
  base-directory: .tmp/s3-staging


