version: 0.2

phases:
  install:
    commands:
      - chmod a+x .codebuild/setup.sh && .codebuild/setup.sh
  pre_build:
    commands:
      - lerna bootstrap
      - lerna exec -- chmod a+x ./codebuild.sh
  build:
    commands:
      - lerna exec -- ./codebuild.sh
      - cd infrastructure && deploy-infrastructure.sh && cd ..

