version: 0.1

phases:
  pre_build:
    commands:
      - yarn install
  # Insert stuff to set up the CDN
  build:
    commands:
      - node index.js

artifacts:
  files:
    - '**/*'
  base-directory: .tmp/s3-staging


