---
version: 1

name: web-community-cdn

pipelines:
  prod:
    phases:
      - type: github
        name: GitHub
        owner: byuweb
        repo: web-cdn
        branch: master
      - type: codebuild
        name: Build
        build_image: aws/codebuild/docker:1.12.1
        environment_variables:
          ENV: prod
        build_role: web-community-cdn-cfn-deploy
      - type: slack_notify
        name: Notify
        message: "Prod CDN Assembler Build Finished"
        channel: "@josephmoore"
  beta:
    phases:
      - type: github
        name: GitHub
        owner: byuweb
        repo: web-cdn
        branch: beta
      - type: codebuild
        name: Build
        build_image: aws/codebuild/docker:1.12.1
        environment_variables:
          ENV: beta
        build_role: web-community-cdn-cfn-deploy
      - type: slack_notify
        name: Notify
        message: "Beta CDN Assembler Build Finished"
        channel: "@josephmoore"
  dev:
    phases:
      - type: github
        name: GitHub
        owner: byuweb
        repo: web-cdn
        branch: beta
      - type: codebuild
        name: Build
        build_image: aws/codebuild/docker:1.12.1
        environment_variables:
          ENV: dev
        build_role: web-community-cdn-cfn-deploy
      - type: slack_notify
        name: Notify
        message: "Dev CDN Assembler Build Finished"
        channel: "@josephmoore"

