---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prod
Resources:
  AliasResolverFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./../alias-resolver-lambda/
      Handler: lambda.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 3
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/web-community-cdn/edge-lambda"
    Tags:
      - Key: Name
        Value: !Join [ " ", [ !FindInMap [ Bucket, !Ref Environment, name ], Web Community CDN Alias Resolver @Edge ] ]
      - Key: team
        # This isn't necessarily accurate, but it's the best group I can find for it.
        Value: OIT_APP_DEV__STUDENT_LIFE_APPS
      - Key: env
        Value: !Ref Environment
      - Key: data-sensitivity
        Value: public
      - Key: app
        Value: Web Community CDN

Outputs:
  AliasResolverName:
    Value: !Ref AliasResolverFunc
  AliasResolverArn:
    Value: !GetAtt AliasResolverFunc.Arn
