---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prod
  RolesStackName:
    Type: String
    Description: CFN stack name of the Roles stack
    Default: web-community-cdn-roles
  HostingStackName:
    Type: String
    Description: CFN stack name of the hosting stack

Mappings:
  CdnHostMap:
    prod:
      root: cdn.byu.edu
    stg:
      root: beta.cdn.byu.edu
    dev:
      root: dev.cdn.byu.edu
      
Resources:
  CdnBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "web-community-cdn-${Environment}-assembler-test"
      Description: Assembles, builds, and deploys the contents of the BYU Web Community CDN
      Artifacts:
        Type: no_artifacts
      Source:
        Type: GITHUB
        Location: https://github.com/byuweb/web-cdn.git
        Auth:
          Type: OAUTH
        BuildSpec: buildspec-assembler.yml
      TimeoutInMinutes: 10
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/web-community-cdn-assembler:${Environment}"
        EnvironmentVariables:
          - Name: DESTINATION_S3_BUCKET
            Value:
              Fn::ImportValue: !Sub "${HostingStackName}-ContentBucket"
          - Name: BUILD_ENV
            Value: !Ref Environment
          - Name: CDN_HOST
            Value: !FindInMap [CdnHostMap, !Ref Environment, root]
      ServiceRole:
        Fn::ImportValue: !Sub "${RolesStackName}-BuilderRole"
      Tags:
        - Key: Name
          Value: !Sub "Web Community CDN ${Environment} Assembler"
        - Key: team
          # This isn't necessarily accurate, but it's the best group I can find for it.
          Value: OIT_APP_DEV__STUDENT_LIFE_APPS
        - Key: env
          Value: !Ref Environment
        - Key: data-sensitivity
          Value: public
        - Key: app
          Value: Web Community CDN

