---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    Default: dev
    AllowedValues:
      - dev
      - stg
      - prod
Mappings:
  DNSSubdomainMap:
    # cleanRoot exists because there's no good way to remove the final . on the root, and we can't change it without
    #   killing the existing zone
    prod:
      root: cdn.byu.edu
      webhooks: webhooks.cdn.byu.edu
    stg:
      root: beta.cdn.byu.edu
      webhooks: webhooks-beta.cdn.byu.edu
    dev:
      root: dev.cdn.byu.edu
      webhooks: webhooks-dev.cdn.byu.edu
Conditions: 
  FlatDns: !Or [ !Equals [ !Ref Environment, dev ], !Equals [ !Ref Environment, stg ] ]
  NestedDns: !Equals [ !Ref Environment, prod ]
Resources:
  DNS:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Join [ " ", [ !Ref Environment, Web Community CDN DNS Zone ] ]
      Name: !Sub
        - ${Domain}.
        - { Domain: !FindInMap [ DNSSubdomainMap, !Ref Environment, root ] }
      HostedZoneTags:
      - Key: Name
        Value: !Join [ " ", [ !FindInMap [ DNSSubdomainMap, !Ref Environment, root ], Web Community CDN DNS Zone ] ]
      - Key: team
        # This isn't necessarily accurate, but it's the best group I can find for it.
        Value: OIT_APP_DEV__STUDENT_LIFE_APPS
      - Key: env
        Value: !Ref Environment
      - Key: data-sensitivity
        Value: public
      - Key: app
        Value: Web Community CDN
    DeletionPolicy: Retain
  WebhookDNS:
    Type: AWS::Route53::HostedZone
    Condition: FlatDns
    Properties:
      HostedZoneConfig:
        Comment: !Join [ " ", [ !Ref Environment, Web Community CDN Webhooks DNS Zone ] ]
      Name: !FindInMap [ DNSSubdomainMap, !Ref Environment, webhooks ]
      HostedZoneTags:
      - Key: Name
        Value: !Join [ " ", [ !FindInMap [ DNSSubdomainMap, !Ref Environment, root ], Web Community CDN Webhooks DNS Zone ] ]
      - Key: team
        # This isn't necessarily accurate, but it's the best group I can find for it.
        Value: OIT_APP_DEV__STUDENT_LIFE_APPS
      - Key: env
        Value: !Ref Environment
      - Key: data-sensitivity
        Value: public
      - Key: app
        Value: Web Community CDN
    DeletionPolicy: Retain

Outputs:
  DNSZone:
    Description: Old DNS Zone ID Output
    Value: !Ref DNS
    Export:
      Name: !Sub "${AWS::StackName}-DNS"
  RootDnsName:
    Description: Root DNS Name
    Value: !FindInMap [ DNSSubdomainMap, !Ref Environment, root ]
    Export:
      Name: !Sub "${AWS::StackName}-RootDnsName"
  RootDnsZoneId:
    Description: Root DNS Zone ID
    Value: !Ref DNS
    Export:
      Name: !Sub "${AWS::StackName}-RootDnsZoneId"
  RootDnsNameServers:
    Description: Root DNS Name Servers
    Value: !Join [ ";", !GetAtt DNS.NameServers ]
    
  WebhookDnsName:
    Description: Webhook DNS Name
    Value: !FindInMap [ DNSSubdomainMap, !Ref Environment, webhooks ]
    Export:
      Name: !Sub "${AWS::StackName}-WebhookDnsName"
  NestedWebhookDnsZoneId:
    Condition: NestedDns
    Description: Webhook DNS Zone ID
    Value: !Ref DNS
    Export:
      Name: !Sub "${AWS::StackName}-WebhookDnsZoneId"
  FlatWebhookDnsZoneId:
    Condition: FlatDns
    Description: Webhook DNS Zone ID
    Value: !Ref WebhookDNS
    Export:
      Name: !Sub "${AWS::StackName}-WebhookDnsZoneId"
  WebhookDnsNameServers:
    Condition: FlatDns
    Description: Webhook DNS Name Servers
    Value: !Join [ ";", !GetAtt DNS.NameServers ]
