version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - $(aws ecr get-login --region $AWS_REGION)
      - TAG=$ENV
      - if [ $ENV = "beta" ]; then TAG=stg; fi
      - IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/web-community-cdn-assembler:$TAG
  build:
    commands:
      - echo Building Docker image
      - docker build . -t $IMAGE
      - echo "Run tests"
      - docker run --rm -i $IMAGE /bin/sh -c 'cd $ASSEMBLER_HOME; npm install; npm test'
      - echo Pushing image as $IMAGE
      - docker push $IMAGE
